name: snap_chef
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  firebase_core: ^3.6.0
  flutter_native_splash: ^2.4.5
  smooth_page_indicator: ^1.0.0

  get: ^4.7.2
  get_storage: ^2.1.1

  http: ^1.0.1
  intl: ^0.18.0
  logger: ^1.0.1
  url_launcher: ^6.3.1


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding_img/
    - assets/logo/
