// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMQyW1mY-7UKm2wzSKP5Q_RldTXAqj-og',
    appId: '1:231582877152:web:17c9671bdd71d621edd785',
    messagingSenderId: '231582877152',
    projectId: 'snap-chef-a1b5c',
    authDomain: 'snap-chef-a1b5c.firebaseapp.com',
    storageBucket: 'snap-chef-a1b5c.firebasestorage.app',
    measurementId: 'G-E19BX8W954',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAUF_L7CwQx4T4ahP0tcwsdUl8Xeu061E',
    appId: '1:231582877152:android:03f72476655ffad0edd785',
    messagingSenderId: '231582877152',
    projectId: 'snap-chef-a1b5c',
    storageBucket: 'snap-chef-a1b5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEvgZ1HPytuejVstNk24Q2A6AFcl1ZwPs',
    appId: '1:231582877152:ios:615c11bae2245c00edd785',
    messagingSenderId: '231582877152',
    projectId: 'snap-chef-a1b5c',
    storageBucket: 'snap-chef-a1b5c.firebasestorage.app',
    iosBundleId: 'com.example.snapChef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEvgZ1HPytuejVstNk24Q2A6AFcl1ZwPs',
    appId: '1:231582877152:ios:615c11bae2245c00edd785',
    messagingSenderId: '231582877152',
    projectId: 'snap-chef-a1b5c',
    storageBucket: 'snap-chef-a1b5c.firebasestorage.app',
    iosBundleId: 'com.example.snapChef',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMQyW1mY-7UKm2wzSKP5Q_RldTXAqj-og',
    appId: '1:231582877152:web:b0fe0bf0adcc9427edd785',
    messagingSenderId: '231582877152',
    projectId: 'snap-chef-a1b5c',
    authDomain: 'snap-chef-a1b5c.firebaseapp.com',
    storageBucket: 'snap-chef-a1b5c.firebasestorage.app',
    measurementId: 'G-EGHSFF7JZJ',
  );
}
